require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - Guardfile
    - 'bin/*'
    - Rakefile
    - 'config/**/*'
    - db/migrate/*
    - config.ru
    - db/*
    - vendor/**/*
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Enabled: true
  Exclude:
    - spec/**/*

Style/Lambda:
  EnforcedStyle: literal
